config/routes.rb
Uxme::Application.routes.draw do

  root to: 'pages#home'
  # match '/ui(/:action)', controller: 'ui'
  match '/thanks', to: "pages#thanks", as: :thanks
  match '/about', to: "pages#about", as: :about
  match '/process', to: "pages#our_process", as: :process
  match '/contact', to: "pages#contact", as: :contact

  resources :quotes
  resources :pages

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :company, :email, :first_name, :last_name, :phone_number, :project_description

  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :project_description, presence: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :prepare_for_mobile

  private

  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS|iPhone/
    end
  end
  helper_method :mobile_device?

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
    render :layout => 'quotes'
  end

  def contact
    render :layout => 'quotes'
  end

  def our_process
    render :layout => 'quotes'
  end

  def thanks
    render :layout => 'quotes'
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

expose(:quote)

  def new
    render :layout => 'quotes'
  end

  def index
    redirect_to root_path
  end

  def create
    if quote.save
      redirect_to thanks_path
      # RequesterMailer.request_quote_email(quote).deliver
    else
      render action: "new"
    end
  end
end

app/controllers/ui_controller.rb
class UiController < Hashrocket::UiController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  = content_tag :div, message, :id => "flash_#{type}", :class => "flash #{type}" do
    %p= message

app/views/layouts/_footer.html.haml
.footer
  .logo
    %h1
      = link_to "UX", root_path
      %span
        = link_to "me.", root_path
  %h4
    a ruby-on-rails and user experience design consultancy
  %p
    copyright © 2012 UXme., Inc.

app/views/layouts/_footer.mobile.haml
.footer
  %ul.navigation
    %li#about
      = link_to 'About', '#'
    %li#process
      = link_to 'Process', '#'
    %li#contact
      = link_to 'Contact', '#'

app/views/layouts/_header.html.haml
%header
  .container
    .logo
      %img
        = link_to image_tag("uxme_iceberg_small.png"), root_path
      %h1
        = link_to "UX", root_path
        %span
          = link_to "me.", root_path
      %h2
        = link_to "designing beautiful experiences", root_path
    %ul.navigation
      %li#about
        = link_to 'About', '#'
      %li#process
        = link_to 'Process', '#'
      %li#contact
        = link_to 'Contact', '#'

app/views/layouts/_header.mobile.haml
%header
  .container
    .logo
      %img
        = link_to image_tag("uxme_iceberg_small.png"), root_path
      %h1
        = link_to "UX", root_path
        %span
          = link_to "me.", root_path
      %h2
        = link_to "designing beautiful experiences", root_path

app/views/layouts/_header2.html.haml
%header
  .container
    .logo
      %img
        = link_to image_tag("uxme_iceberg_small.png"), root_path
      %h1
        = link_to "UX", root_path
        %span
          = link_to "me.", root_path
      %h2
        = link_to "designing beautiful experiences", root_path
    %ul.navigation
      %li#about
        = link_to 'About', about_path
      %li#process
        = link_to 'Process', process_path
      %li#contact
        = link_to 'Contact', contact_path

app/views/layouts/_typekit.erb
<script type="text/javascript" src="//use.typekit.net/djo8lpt.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

app/views/layouts/_typekit.html.erb
<script type="text/javascript" src="//use.typekit.net/djo8lpt.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      UXme. | Rails and UX Consulting
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render 'layouts/typekit'
    = yield :head
    / /[if IE]
    /   = javascript_include_tag 'html5'
  %body
    #main
      = render 'layouts/header'
      = render 'layouts/flash', flash: flash
      = yield
    = render 'layouts/footer'

app/views/layouts/application.mobile.haml
!!!
%html
  %head
    %title
      UXme. | Rails and UX Consulting
    = stylesheet_link_tag    'application'
    = stylesheet_link_tag    'mobile' if mobile_device?
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render 'layouts/typekit'
    = yield :head
    / /[if IE]
    /   = javascript_include_tag 'html5'
  %body
    #main
      = render 'layouts/header'
      / = render 'layouts/flash', flash: flash
      = yield
      = render 'layouts/footer'

app/views/layouts/quotes.html.haml
!!!
%html
  %head
    %title
      UXme. | Rails and UX Consulting
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render 'layouts/typekit'
    = yield :head
    / /[if IE]
    /   = javascript_include_tag 'html5'
  %body
    #main
      = render 'layouts/header2'
      = render 'layouts/flash', flash: flash
      = yield
    = render 'layouts/footer'

app/views/pages/about.html.haml
#about-page
  .container
    .welovewhitespace
      %h1#about
        About
        %span.ux#about
          UX
        %span#about
          me.
      %p
        UXme. is a web development and user experience design boutique. We
        specialize in Ruby-on-Rails development of beautiful, powerful web
        applications. We care about only one thing: your user. Every decision we
        make is centered around your users, your customers.
      %p
        Our development philosophy is simple, what you leave off the page is as
        important as what you leave on. If Ernest Hemingway were a web
        developer, he'd work for us.
      %p.whitespace
        We love whitespace.
      #pullquote
        %blockquote.pquote
          %p
            We love simple, bold and ultra-minimal.
      %p.whitespace
        We use color only when there is a good reason to do so.
      %p
        UXme. web applications are about speed, elegance and simplicity. If you
        want your site to look like Yahoo.com, don't contact us. If you want your
        site to have to simple elegance of the Google home page, then we should
        talk. If you need help turning your great idea into something beautiful,
        then we'd love to help.
      %p
        UXme. was founded by Brian Dear, a New York City UX and Ruby-on-Rails
        consultant. He is the cofounder of #{link_to "iCouch.me", "http://icouch.me"}
        and the developer of the best-selling iOS therapy app, #{link_to "iCouch CBT", "http://itunes.apple.com/us/app/icouch-cbt/id446115508?mt=8"}.
      %h2#simple
        Just because it's simple, doesn't mean it's easy.
      #cta-button
        %li#cta
          = link_to "Get a quote now", new_quote_path
      %h2#simple

app/views/pages/contact.html.haml
#contact-page
  .container
    .welovewhitespace
      %h1#about
        Contact
        %span.ux#about
          UX
        %span#about
          me.
      %h2
        = mail_to('brian@icouch.me', image_tag('envelope.jpg'))
      %h2
        = link_to image_tag('twitter.png'), 'http://twitter.com/superacidjax'
      #cta-button
        %li#cta
          = link_to "Get a quote now", new_quote_path

app/views/pages/home.html.haml
%content
  #headline-section
    .container
      .hemingway
        %h3#typing
          If a designer of web applications knows enough about what he's trying to communicate, he may omit things that he knows and the user will have a feeling of those things as strongly as though the designer has put them on the page. The dignity of movement of the iceberg is due to only one-eighth of it being above water.
        %h4#byline
          &#8212; Ernest Hemingway
        %h5#parens
          (if he were a web developer)
        %h1#icebergs
          We build icebergs.
        #cta-button
          %li#cta
            = link_to "Get a quote now", new_quote_path
  #quote-section
    / = render partial: 'quotes/new', object: quote
  #about-section
    .container
      .welovewhitespace
        %h1#about
          About
          %span.ux#about
            UX
          %span#about
            me.
        %p
          UXme. is a web development and user experience design boutique. We
          specialize in Ruby-on-Rails development of beautiful, powerful web
          applications. We care about only one thing: your user. Every decision we
          make is centered around your users, your customers.
        %p
          Our development philosophy is simple, what you leave off the page is as
          important as what you leave on. If Ernest Hemingway were a web
          developer, he'd work for us.
        %p.whitespace
          We love whitespace.
        #pullquote
          %blockquote.pquote
            %p
              We love simple, bold and ultra-minimal.
        %p.whitespace
          We use color only when there is a good reason to do so.
        %p
          UXme. web applications are about speed, elegance and simplicity. If you
          want your site to look like Yahoo.com, don't contact us. If you want your
          site to have to simple elegance of the Google home page, then we should
          talk. If you need help turning your great idea into something beautiful,
          then we'd love to help.
        %p
          UXme. was founded by Brian Dear, a New York City UX and Ruby-on-Rails
          consultant. He is the cofounder of #{link_to "iCouch.me", "http://icouch.me"}
          and the developer of the best-selling iOS therapy app, #{link_to "iCouch CBT", "http://itunes.apple.com/us/app/icouch-cbt/id446115508?mt=8"}.
        %h2#simple
          Just because it's simple, doesn't mean it's easy.
        #cta-button
          %li#cta
            = link_to "Get a quote now", new_quote_path
        %h2#simple

  #process-section
    .container
      .weloveprocess
        %h1
          The
          %span.ux
            UX
          %span
            me.
          Process
        %p
          With the proliferation of do-it-yourself website building tools, creating
          a web application is easier than ever. However, creating an effective,
          beautiful and elegant web application takes experience in not only design
          and programming, it also requires business experience. While it's not
          particularly hard to copy designs of successful websites, those websites
          are not
          %strong
            your
          business.
        %p
          Every business has something special to offer their customers and every
          business website should have only one goal: to convince visitors to take
          action. That action could be buying your product, asking for a quote,
          or visiting your store. Every decision in crafting your web application
          should always be focused on achieving that one goal.
        %p
          UXme. is Agile. We collaborate with you. Of course, you're the client
          and you're paying the bills, but creating an incredible web application
          is a team effort. We consider you an active partner and participant in
          all stages of the process.
        .circle
          = image_tag "step_one.png"
        %h2#process
          Discovery
        %p
          Discovery is fun. This is where the sky is the limit and budgets
          don't matter. We work with you to understand your business, your goals
          and your personality.
        %p
          This is when you can use your imagination. Perhaps we'll sketch on napkins,
          share photos and other websites that best communicate the look you want.
          During Discovery, we provide guidance, inspiration and experience to help
          you articulate your ideas.
        .circle
          = image_tag "step_two.png"
        %h2#process
          Story Carding
        %p
          Story Carding is where we act like a user. We decide on what a user should
          do on your site, from when they first visit your landing page until they
          tell their friends how great your product is.
        %p
          We'll build wireframes that allow you to see your site before it's actually
          built. Wireframes are like precision sketches that help you and us
          visualize the major elements and interactions of your site. This is an
          important step because it allows us to test ideas without the time expense
          of writing code or doing highly-detailed photoshop mockups.
        .circle
          = image_tag "step_three.png"
        %h2#process
          Design
        %p
          After we complete the wireframes for your site, we're ready to start
          choosing the typography, graphics and other elements for your site. Design
          is far more than just making your site look pretty. Great design is
          fundamental to making your users love your site (and buy what you're
          selling!)
        %p
          All design has one purpose: to enhance the user experience.
        .circle
          = image_tag "step_four.png"
        %h2#process
          Coding
        %p
          Coding is where the rubber meets the road. We turn the design elements
          and the wireframes into a fully functional site.
        %p
          You'll be our partner through the process. You'll interact with the site
          as it's being built. We set up a "staging" server that allows you to use
          your web application and provide very important feedback throughout the
          process. You'll be in regular communication with us on all aspects of
          the coding process.
        .circle
          = image_tag "step_five.png"
        %h2#process
          Rinse & Repeat
        %p
          After we create a working prototype of your site, the work isn't done!
          We'll launch your site and then observe how users interact with your
          web application. This is where we'll make refinements, fix any errors and
          improve upon things. We might add new features, take some out or redesign
          elements.
        %p
          For as long as you'd like us involved with your project, we're your
          technical and business consultants. Our goal is to create a web application
          that will serve your business for years to come.
        #cta-button
          %li#cta
            = link_to "Get a quote now", '#'
        %h2#simple
        %br
        %br
  #contact-section
    .container
      .welovewhitespace
        %h1#about
          Contact
          %span.ux#about
            UX
          %span#about
            me.
        %h2
          = mail_to('brian@icouch.me', image_tag('envelope.jpg'))
        %h2
          = link_to image_tag('twitter.png'), 'http://twitter.com/superacidjax'
        #cta-button
          %li#cta
            = link_to "Get a quote now", new_quote_path
          %br
          %br

app/views/pages/home.mobile.haml
%content
  #headline-section
    .container
      .hemingway
        %h3#typing
          If a designer of web applications knows enough about what he's trying to communicate, he may omit things that he knows and the user will have a feeling of those things as strongly as though the designer has put them on the page. The dignity of movement of the iceberg is due to only one-eighth of it being above water.
        %h4#byline
          &#8212; Ernest Hemingway
        %h5#parens
          (if he were a web developer)
        %h1#icebergs
          We build icebergs.
        #cta-button
          %li#cta
            = link_to "Get a quote now", new_quote_path
  #quote-section
    / = render partial: 'quotes/new', object: quote
  #about-section
    .container
      .welovewhitespace
        %h1#about
          About
          %span.ux#about
            UX
          %span#about
            me.
        %p
          UXme. is a web development and user experience design boutique. We
          specialize in Ruby-on-Rails development of beautiful, powerful web
          applications. We care about only one thing: your user. Every decision we
          make is centered around your users, your customers.
        %p
          Our development philosophy is simple, what you leave off the page is as
          important as what you leave on. If Ernest Hemingway were a web
          developer, he'd work for us.
        %p.whitespace
          We love whitespace.
        #pullquote
          %blockquote.pquote
            %p
              We love simple, bold and ultra-minimal.
        %p.whitespace
          We use color only when there is a good reason to do so.
        %p
          UXme. web applications are about speed, elegance and simplicity. If you
          want your site to look like Yahoo.com, don't contact us. If you want your
          site to have to simple elegance of the Google home page, then we should
          talk. If you need help turning your great idea into something beautiful,
          then we'd love to help.
        %p
          UXme. was founded by Brian Dear, a New York City UX and Ruby-on-Rails
          consultant. He is the cofounder of #{link_to "iCouch.me", "http://icouch.me"}
          and the developer of the best-selling iOS therapy app, #{link_to "iCouch CBT", "http://itunes.apple.com/us/app/icouch-cbt/id446115508?mt=8"}.
        %h2#simple
          Just because it's simple, doesn't mean it's easy.
        #cta-button
          %li#cta
            = link_to "Get a quote now", new_quote_path
        %h2#simple

  #process-section
    .container
      .weloveprocess
        %h1
          The
          %span.ux
            UX
          %span
            me.
          Process
        %p
          With the proliferation of do-it-yourself website building tools, creating
          a web application is easier than ever. However, creating an effective,
          beautiful and elegant web application takes experience in not only design
          and programming, it also requires business experience. While it's not
          particularly hard to copy designs of successful websites, those websites
          are not
          %strong
            your
          business.
        %p
          Every business has something special to offer their customers and every
          business website should have only one goal: to convince visitors to take
          action. That action could be buying your product, asking for a quote,
          or visiting your store. Every decision in crafting your web application
          should always be focused on achieving that one goal.
        %p
          UXme. is Agile. We collaborate with you. Of course, you're the client
          and you're paying the bills, but creating an incredible web application
          is a team effort. We consider you an active partner and participant in
          all stages of the process.
        .circle
          = image_tag "step_one.png"
        %h2#process
          Discovery
        %p
          Discovery is fun. This is where the sky is the limit and budgets
          don't matter. We work with you to understand your business, your goals
          and your personality.
        %p
          This is when you can use your imagination. Perhaps we'll sketch on napkins,
          share photos and other websites that best communicate the look you want.
          During Discovery, we provide guidance, inspiration and experience to help
          you articulate your ideas.
        .circle
          = image_tag "step_two.png"
        %h2#process
          Story Carding
        %p
          Story Carding is where we act like a user. We decide on what a user should
          do on your site, from when they first visit your landing page until they
          tell their friends how great your product is.
        %p
          We'll build wireframes that allow you to see your site before it's actually
          built. Wireframes are like precision sketches that help you and us
          visualize the major elements and interactions of your site. This is an
          important step because it allows us to test ideas without the time expense
          of writing code or doing highly-detailed photoshop mockups.
        .circle
          = image_tag "step_three.png"
        %h2#process
          Design
        %p
          After we complete the wireframes for your site, we're ready to start
          choosing the typography, graphics and other elements for your site. Design
          is far more than just making your site look pretty. Great design is
          fundamental to making your users love your site (and buy what you're
          selling!)
        %p
          All design has one purpose: to enhance the user experience.
        .circle
          = image_tag "step_four.png"
        %h2#process
          Coding
        %p
          Coding is where the rubber meets the road. We turn the design elements
          and the wireframes into a fully functional site.
        %p
          You'll be our partner through the process. You'll interact with the site
          as it's being built. We set up a "staging" server that allows you to use
          your web application and provide very important feedback throughout the
          process. You'll be in regular communication with us on all aspects of
          the coding process.
        .circle
          = image_tag "step_five.png"
        %h2#process
          Rinse & Repeat
        %p
          After we create a working prototype of your site, the work isn't done!
          We'll launch your site and then observe how users interact with your
          web application. This is where we'll make refinements, fix any errors and
          improve upon things. We might add new features, take some out or redesign
          elements.
        %p
          For as long as you'd like us involved with your project, we're your
          technical and business consultants. Our goal is to create a web application
          that will serve your business for years to come.
        #cta-button
          %li#cta
            = link_to "Get a quote now", '#'
        %h2#simple
        %br
        %br
  #contact-section
    .container
      .welovewhitespace
        %h1#about
          Contact
          %span.ux#about
            UX
          %span#about
            me.
        %h2
          = mail_to('brian@icouch.me', image_tag('envelope.jpg'))
        %h2
          = link_to image_tag('twitter.png'), 'http://twitter.com/superacidjax'
        #cta-button
          %li#cta
            = link_to "Get a quote now", new_quote_path
          %br
          %br

app/views/pages/our_process.html.haml
#process-page
  .container
    .weloveprocess
      %h1
        The
        %span.ux
          UX
        %span
          me.
        Process
      %p
        With the proliferation of do-it-yourself website building tools, creating
        a web application is easier than ever. However, creating an effective,
        beautiful and elegant web application takes experience in not only design
        and programming, it also requires business experience. While it's not
        particularly hard to copy designs of successful websites, those websites
        are not
        %strong
          your
        business.
      %p
        Every business has something special to offer their customers and every
        business website should have only one goal: to convince visitors to take
        action. That action could be buying your product, asking for a quote,
        or visiting your store. Every decision in crafting your web application
        should always be focused on achieving that one goal.
      %p
        UXme. is Agile. We collaborate with you. Of course, you're the client
        and you're paying the bills, but creating an incredible web application
        is a team effort. We consider you an active partner and participant in
        all stages of the process.
      .circle
        = image_tag "step_one.png"
      %h2#process
        Discovery
      %p
        Discovery is fun. This is where the sky is the limit and budgets
        don't matter. We work with you to understand your business, your goals
        and your personality.
      %p
        This is when you can use your imagination. Perhaps we'll sketch on napkins,
        share photos and other websites that best communicate the look you want.
        During Discovery, we provide guidance, inspiration and experience to help
        you articulate your ideas.
      .circle
        = image_tag "step_two.png"
      %h2#process
        Story Carding
      %p
        Story Carding is where we act like a user. We decide on what a user should
        do on your site, from when they first visit your landing page until they
        tell their friends how great your product is.
      %p
        We'll build wireframes that allow you to see your site before it's actually
        built. Wireframes are like precision sketches that help you and us
        visualize the major elements and interactions of your site. This is an
        important step because it allows us to test ideas without the time expense
        of writing code or doing highly-detailed photoshop mockups.
      .circle
        = image_tag "step_three.png"
      %h2#process
        Design
      %p
        After we complete the wireframes for your site, we're ready to start
        choosing the typography, graphics and other elements for your site. Design
        is far more than just making your site look pretty. Great design is
        fundamental to making your users love your site (and buy what you're
        selling!)
      %p
        All design has one purpose: to enhance the user experience.
      .circle
        = image_tag "step_four.png"
      %h2#process
        Coding
      %p
        Coding is where the rubber meets the road. We turn the design elements
        and the wireframes into a fully functional site.
      %p
        You'll be our partner through the process. You'll interact with the site
        as it's being built. We set up a "staging" server that allows you to use
        your web application and provide very important feedback throughout the
        process. You'll be in regular communication with us on all aspects of
        the coding process.
      .circle
        = image_tag "step_five.png"
      %h2#process
        Rinse & Repeat
      %p
        After we create a working prototype of your site, the work isn't done!
        We'll launch your site and then observe how users interact with your
        web application. This is where we'll make refinements, fix any errors and
        improve upon things. We might add new features, take some out or redesign
        elements.
      %p
        For as long as you'd like us involved with your project, we're your
        technical and business consultants. Our goal is to create a web application
        that will serve your business for years to come.
      #cta-button
        %li#cta
          = link_to "Get a quote now", new_quote_path
      %h2#simple
      %br
      %br

app/views/pages/projects.html.haml
%h1 Pages#projects
%p Find me in app/views/pages/projects.html.haml

app/views/pages/thanks.html.haml
#thanks
  %h1#thanks
    Thanks!
  %h2#thanks
    We'll be in touch very soon.

app/views/quotes/_new.html.haml
%content
  #request-quote-section
    .container
      .welovequotes
        %h1
          Request a quote
        %p
          UXme. typically works on a project basis, billed hourly. Regardless
          of your budget, we'd love to discuss your project in detail. Even if
          you don't end up as our client, we're always happy to provide free suggestions, advice and experienced guidance for your project. We'll
          even recommend other consultancies if your project is something that might be better served by another company. Even if you don't become
          our client, you're certainly become our friend!
    #form
      - if quote.errors.any?
        #error_explanation
          %div
            This form contains #{pluralize(quote.errors.count, "error")}
          %ul
            - quote.errors.full_messages.each do |msg|
              %li
                = msg
      = semantic_form_for(quote) do |f|
        = f.input :first_name, label: "First name *"
        = f.input :last_name, label: "Last name *"
        = f.input :company
        = f.input :email, as: :email, label: "Email *"
        = f.input :phone_number, as: :phone
        = f.input :project_description, label: "Project description *", as: :text, :input_html => { :class => 'autogrow', :rows => 10, :cols => 50  }
        = f.action :submit, label: "Send"
        = f.action :cancel, :as => :link, label: "cancel"

app/views/quotes/new.html.haml
%content
  #request-quote-section
    .container
      .welovequotes
        %h1
          Request a quote
        %p
          UXme. typically works on a project basis, billed hourly. Regardless
          of your budget, we'd love to discuss your project in detail. Even if
          you don't end up as our client, we're always happy to provide free suggestions, advice and experienced guidance for your project. We'll
          even recommend other consultancies if your project is something that might be better served by another company. Even if you don't become
          our client, you're certainly become our friend!
    #form
      = semantic_form_for(quote) do |f|
        - if quote.errors.any?
          #error_explanation
            %div
              This form contains #{pluralize(quote.errors.count, "error")}
            %ul
              - quote.errors.full_messages.each do |msg|
                %li
                  = msg
        = f.input :first_name, label: "First name *"
        = f.input :last_name, label: "Last name *"
        = f.input :company
        = f.input :email, as: :email, label: "Email *"
        = f.input :phone_number, as: :phone
        = f.input :project_description, label: "Project description *", as: :text, :input_html => { :class => 'autogrow', :rows => 10, :cols => 50  }
        = f.action :submit, label: "Send"
        #cancel
          = f.action :cancel, :as => :link, label: "cancel"
        %br
        %br